### PR TITLE
#527: manage align

### PR DESCRIPTION
**Pull request by prajwol5667**

### CODE REVIEW

**Comment by SadiaRasheed** [comment]
Code seems fine.

*Sadia Rasheed | Software Engineer*
Skype: sadiarasheed.nbs
*NorthBay Solutions (Pvt.) Ltd.*
*Address: 410 G4, Johar Town, Lahore.*

**Comment by dogi** [comment]
@prajwol5667 and @SadiaRasheed 

`"uploaded_file":"Uploaded File :",`
is part of a language file

which by old policy need to be added in all (4) languages files
and by new policy also to the Text.json file

**Comment by SadiaRasheed** [comment]
@prajwol566 : 
Please add this or should I add this in all the files?

**Comment by dogi** [comment]
awesome this look ready to go now

**Pull request merged**
