### PR TITLE
Upload couchapp as zip - fixes #607

### LINKED ISSUE #607: Look into adding html resources to couchdb via Javascript/HTTP
Right now we use a [round about method](http://open-learning-exchange.github.io/#!pages/htmlresources.md) to get html apps into BeLL/Couch. It would be nice if users could select a folder containing a html app and add it to bell without having to use or know about couchapp. Since CouchDB supports HTTP, and there are already CouchDB wrappers, this should be possible. Essentially we just need to duplicate some of the functionality of CouchApp in javascript. If anyone has information or ideas on how we can go about doing this, please comment.

### PR DESCRIPTION
**Pull request by paulbert**
Here's a solution I have working locally for #607 that is ready for some testing.

To add a CouchApp/HTMLapp with this update you will need to:

1. Create a zip file with the contents of the CouchApp
2. Go to add new resource and fill out as normal
3. Include the file name that needs to be opened (i.e. `index.html`) in the "Open URL" field of the form
4. Add the zip file as the Upload Resources file

The zip file will then be unpacked and each attachment added to CouchDB.  This process may take a while, and I would like feedback if this will take too long on slower computers than my local machine.

Another change I can foresee is my change of the `openURL` resource property to open the start page of the app.  I had trouble (this is my first time working on a Backbone app) figuring out how to add the `openWhichFile` to the resource form, so changed this field instead so we can test the CouchApp unpack & upload functionality on some more apps.  If the `openURL` field is still needed for its previously written use, then I'll need some guidance on how to add another field to the resource form.

If you don't have a CouchApp handy to test this with, try the [Virtual Intern wiki](https://github.com/open-learning-exchange/open-learning-exchange.github.io)

### CODE REVIEW

**Comment by empeje** [comment]
I will check and confirm the results soon @paulbert

**Comment by dogi** [comment]
@paulbert should I give this a other QA spin ;)

**Review by leomaxi — APPROVED** [review]

**Comment by paulbert** [comment]
I grabbed a vdi file of Ubuntu 16.10 to get a little more insight into the issue, and found I just put the wrong argument into indexOf...

It's working now for me on Ubuntu and I reverted the change for openUrl so that field works as before and opens an absolute URL.

Let me know if you're able to successfully test this.  [Here's a link to download a zip file of the virtual intern wiki](https://drive.google.com/file/d/0B7v_nsaZGnMyWGYxRzRMeWxDMWc/view?usp=sharing) if you need an HTMLapp or would like to test a fairly large one.

**Review by dogi — APPROVED** [review]
congrats  @paulbert

**Comment by lmmrssa** [comment]
@dogi  should i merge it in the next release?

**Comment by dogi** [comment]
@lmmrssa maybe we can do special release tonight ;)
@dogi would <3 to have this on http://vi.ole.org as soon as possible ...

**Pull request merged**
