### PR TITLE
[721]-test view in step detail for manager(connects #721)

### PR DESCRIPTION
**Pull request by Rupesh87**
capturee

### CODE REVIEW

**Review by dogi — CHANGES_REQUESTED** [review]
@Rupesh87 change of 40 files is scaring me ;)

I do think that nobody else then crowdin should change the file `init_docs/languages/*.txt` ...
@lmmrssa wonder about your opinion here

**Review by dogi — CHANGES_REQUESTED** [review]
@Rupesh87 better ;)

this time it looks like you removed too much - `Text.json` was OK

**Comment by Rupesh87** [comment]
@dogi its because initdocs is the copy of init_docs so whole folder was removed.

**Comment by dogi** [comment]
oh I see

@Rupesh87 so you are saying there is even no reason to have `Text.json`, cause it never changed ...

**Review by razu9861 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Review by lmmrssa — APPROVED** [review]

**Review by nirojdyola — APPROVED** [review]

**Pull request closed without merging**
