### PR TITLE
[#1034] Margin set for BeLL-App (connects #1034)

### PR DESCRIPTION
**Pull request by Pr0chin**
- [x] Made new branch for Margin fix
- [x] Made changes in both parent css (Home.css and Home-Urdu.css)
- [x] Removed Inline CSS
- [x] Checked in all Pages if it works or not.

### CODE REVIEW

**Comment by Pr0chin** [comment]
s1
s2
s3
s4
s5
s6
s7
s8
s9
s10
s11
s12
s13
s14
s15
s16
s18
s19
s20
s21
s22

**Comment by Pr0chin** [comment]
as
h

**Review by razu9861 — APPROVED** [review]

**Comment by lmmrssa** [comment]
@razu9861 @Pr0chin  current failing test case is fixed in one PR so please make sure this also passes the test.

**Review by Rupesh87 — APPROVED** [review]

**Review by nirojdyola — APPROVED** [review]

**Review by dogi — COMMENTED** [review]
@Pr0chin why is language test still turned off?

**Comment by Rupesh87** [comment]
@dogi language test are failing in all test so that we have turn off the language test..

**Comment by Pr0chin** [comment]
yes @dogi

**Pull request merged**
