### PR TITLE
Reenabling 4 tests for issue #948

### PR DESCRIPTION
**Pull request by duongdo27**
Hi @dogi, I rename the 4 tests back to the original. 
- [ ] tests/addReport_test.js
- [ ] tests/feedback_test.js
- [ ] tests/meetup_test.js
- [ ] tests/resource_test.js

### CODE REVIEW

**Comment by dogi** [comment]
@duongdo27 all test fail

**Review by dogi — CHANGES_REQUESTED** [review]
@duongdo27 enabling a test is a start in getting a test working again, but the issue wants you also to fix them

**Comment by duongdo27** [comment]
I see. I will work on it and let you know

**Comment by duongdo27** [comment]
Hi @dogi, I fix 4 tests. Please take a look and give me feedbacks.

**Comment by dogi** [comment]
@duongdo27 look at this
```
The command "i=$(curl -X GET http://127.0.0.1:5981/_all_dbs | jq length); if [ $i -ne 40 ]; then exit 1; fi" exited with 0.
0.97s$ (cd tests && codeceptjs run --steps)
creating output directory: /home/travis/build/open-learning-exchange/BeLL-Apps/tests/output
Cleaning up couchdb.
Set visits to zero.
(node:6215) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token :
(node:6215) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
in
https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds/264591011?utm_source=github_status&utm_medium=notification

**Review by dogi — CHANGES_REQUESTED** [review]
node is broken?

**Pull request closed without merging**
